apiVersion: v1
kind: Service
metadata:
  name: openmars
  labels:
    app.kubernetes.io/name: openmars
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: openmars
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: openmars
  ports:
    - port: 3001
      targetPort: http
      protocol: TCP
      name: http
