// Re-exports from generated types + type guards for the ResourceCondition discriminated union.
// The union type and category interfaces are generated by tygo from Go DTO structs.
// This file provides type guards and convenience re-exports.

import type {
  BasicResourceConditionDto,
  ProductionConditionDto,
  TilePlacementConditionDto,
  GlobalParameterConditionDto,
  CardOperationConditionDto,
  CardStorageConditionDto,
  EffectConditionDto,
  ColonyConditionDto,
  TileModificationConditionDto,
  MiscConditionDto,
  ResourceCondition,
  PerConditionDto,
  SelectorDto,
  TileRestrictionsDto,
  TargetRestrictionDto,
} from "./generated/api-types";

// Re-export generated types for convenience
export type {
  BasicResourceConditionDto,
  ProductionConditionDto,
  TilePlacementConditionDto,
  GlobalParameterConditionDto,
  CardOperationConditionDto,
  CardStorageConditionDto,
  EffectConditionDto,
  ColonyConditionDto,
  TileModificationConditionDto,
  MiscConditionDto,
  ResourceCondition,
};

// --- Type guard functions ---

const basicResourceTypes: Set<string> = new Set([
  "credit",
  "steel",
  "titanium",
  "plant",
  "energy",
  "heat",
]);
const productionTypes: Set<string> = new Set([
  "credit-production",
  "steel-production",
  "titanium-production",
  "plant-production",
  "energy-production",
  "heat-production",
  "any-production",
]);
const tilePlacementTypes: Set<string> = new Set([
  "city-placement",
  "ocean-placement",
  "greenery-placement",
  "volcano-placement",
  "tile-placement",
  "land-claim",
]);
const globalParameterTypes: Set<string> = new Set([
  "temperature",
  "oxygen",
  "ocean",
  "venus",
  "tr",
  "global-parameter",
]);
const cardOperationTypes: Set<string> = new Set([
  "card-draw",
  "card-take",
  "card-peek",
  "card-buy",
  "card-discard",
]);
const cardStorageTypes: Set<string> = new Set([
  "microbe",
  "animal",
  "floater",
  "science",
  "asteroid",
  "fighter",
  "disease",
  "card-resource",
]);
const effectTypes: Set<string> = new Set([
  "discount",
  "payment-substitute",
  "storage-payment-substitute",
  "value-modifier",
  "global-parameter-lenience",
  "ignore-global-requirements",
  "ocean-adjacency-bonus",
  "defense",
  "action-reuse",
  "effect",
  "tag",
]);
const colonyTypes: Set<string> = new Set([
  "colony-tile",
  "colony-count",
  "colony-bonus",
  "colony-track-step",
]);
const tileModificationTypes: Set<string> = new Set(["tile-destruction", "tile-replacement"]);
const miscTypes: Set<string> = new Set([
  "extra-actions",
  "bonus-tags",
  "world-tree-tile",
  "award-fund",
  "trade",
]);

export function isBasicResource(c: ResourceCondition): c is BasicResourceConditionDto {
  return basicResourceTypes.has(c.type);
}

export function isProduction(c: ResourceCondition): c is ProductionConditionDto {
  return productionTypes.has(c.type);
}

export function isTilePlacement(c: ResourceCondition): c is TilePlacementConditionDto {
  return tilePlacementTypes.has(c.type);
}

export function isGlobalParameter(c: ResourceCondition): c is GlobalParameterConditionDto {
  return globalParameterTypes.has(c.type);
}

export function isCardOperation(c: ResourceCondition): c is CardOperationConditionDto {
  return cardOperationTypes.has(c.type);
}

export function isCardStorage(c: ResourceCondition): c is CardStorageConditionDto {
  return cardStorageTypes.has(c.type);
}

export function isEffect(c: ResourceCondition): c is EffectConditionDto {
  return effectTypes.has(c.type);
}

export function isColony(c: ResourceCondition): c is ColonyConditionDto {
  return colonyTypes.has(c.type);
}

export function isTileModification(c: ResourceCondition): c is TileModificationConditionDto {
  return tileModificationTypes.has(c.type);
}

export function isMisc(c: ResourceCondition): c is MiscConditionDto {
  return miscTypes.has(c.type);
}

// --- Field accessors for safe access across the union ---

export function getPer(c: ResourceCondition): PerConditionDto | undefined {
  if ("per" in c) {
    return c.per;
  }
  return undefined;
}

export function getSelectors(c: ResourceCondition): SelectorDto[] | undefined {
  if ("selectors" in c) {
    return c.selectors;
  }
  return undefined;
}

export function getTileRestrictions(c: ResourceCondition): TileRestrictionsDto | undefined {
  if ("tileRestrictions" in c) {
    return c.tileRestrictions;
  }
  return undefined;
}

export function getVariableAmount(c: ResourceCondition): boolean | undefined {
  if ("variableAmount" in c) {
    return c.variableAmount;
  }
  return undefined;
}

export function getTargetRestriction(c: ResourceCondition): TargetRestrictionDto | undefined {
  if ("targetRestriction" in c) {
    return c.targetRestriction;
  }
  return undefined;
}

export function getTileType(c: ResourceCondition): string | undefined {
  if ("tileType" in c) {
    return c.tileType;
  }
  return undefined;
}
