// Re-export WebSocket message type constants from the frontend generated types.

export {
  MessageTypePlayerConnect,
  MessageTypeJoinGame,
  MessageTypeGameUpdated,
  MessageTypePlayerConnected,
  MessageTypePlayerReconnected,
  MessageTypePlayerDisconnected,
  MessageTypeError,
  MessageTypeFullState,
  MessageTypeLogUpdate,
  MessageTypePlayerKicked,
  MessageTypeActionStandardProject,
  MessageTypeActionConfirmSellPatents,
  MessageTypeActionConvertPlantsToGreenery,
  MessageTypeActionConvertHeatToTemperature,
  MessageTypeActionStartGame,
  MessageTypeActionSkipAction,
  MessageTypeActionPlayCard,
  MessageTypeActionCardAction,
  MessageTypeActionSelectStartingChoices,
  MessageTypeActionSelectCards,
  MessageTypeActionConfirmProductionCards,
  MessageTypeActionCardDrawConfirmed,
  MessageTypeActionCardDiscardConfirmed,
  MessageTypeActionBehaviorChoiceConfirmed,
  MessageTypeActionTileSelected,
  MessageTypeActionClaimMilestone,
  MessageTypeActionFundAward,
  MessageTypeActionSelectDemoChoices,
  MessageTypeRequestLogs,
  MessageTypePlayerTakeover,
  MessageTypeKickPlayer,
} from "../../frontend/src/types/generated/api-types.js";
