// Re-export WebSocket message type constants from the frontend generated types.

export {
  MessageTypePlayerConnect,
  MessageTypeJoinGame,
  MessageTypeGameUpdated,
  MessageTypePlayerConnected,
  MessageTypePlayerReconnected,
  MessageTypePlayerDisconnected,
  MessageTypeError,
  MessageTypeFullState,
  MessageTypeLogUpdate,
  MessageTypePlayerKicked,
  MessageTypeActionSellPatents,
  MessageTypeActionConfirmSellPatents,
  MessageTypeActionLaunchAsteroid,
  MessageTypeActionBuildPowerPlant,
  MessageTypeActionBuildAquifer,
  MessageTypeActionPlantGreenery,
  MessageTypeActionBuildCity,
  MessageTypeActionConvertPlantsToGreenery,
  MessageTypeActionConvertHeatToTemperature,
  MessageTypeActionStartGame,
  MessageTypeActionSkipAction,
  MessageTypeActionPlayCard,
  MessageTypeActionCardAction,
  MessageTypeActionSelectStartingChoices,
  MessageTypeActionSelectCards,
  MessageTypeActionConfirmProductionCards,
  MessageTypeActionCardDrawConfirmed,
  MessageTypeActionCardDiscardConfirmed,
  MessageTypeActionBehaviorChoiceConfirmed,
  MessageTypeActionTileSelected,
  MessageTypeActionClaimMilestone,
  MessageTypeActionFundAward,
  MessageTypeActionConfirmDemoSetup,
  MessageTypeRequestLogs,
  MessageTypePlayerTakeover,
  MessageTypeKickPlayer,
} from "../../frontend/src/types/generated/api-types.js";
