// Re-export types from the frontend generated types.
// This avoids duplicating the large generated file.

export type {
  GameDto,
  PlayerDto,
  OtherPlayerDto,
  CardDto,
  PlayerCardDto,
  PlayerActionDto,
  PlayerEffectDto,
  PlayerStandardProjectDto,
  PlayerMilestoneDto,
  PlayerAwardDto,
  ResourcesDto,
  ProductionDto,
  GlobalParametersDto,
  GameSettingsDto,
  BoardDto,
  TileDto,
  TileBonusDto,
  TileOccupantDto,
  HexPositionDto,
  CardPaymentDto,
  CardBehaviorDto,
  ResourceCondition,
  ChoiceDto,
  CardRequirementsDto,
  RequirementDto,
  ResourceStorageDto,
  VPConditionDto,
  PerConditionDto,
  MilestoneDto,
  AwardDto,
  AwardResultDto,
  FinalScoreDto,
  VPBreakdownDto,
  PendingTileSelectionDto,
  PendingCardSelectionDto,
  PendingCardDrawSelectionDto,
  PendingCardDiscardSelectionDto,
  PendingBehaviorChoiceSelectionDto,
  ForcedFirstActionDto,
  PaymentConstantsDto,
  PaymentSubstituteDto,
  StoragePaymentSubstituteDto,
  SelectCorporationPhaseDto,
  SelectStartingCardsPhaseDto,
  SelectPreludeCardsPhaseDto,
  ProductionPhaseDto,
  WebSocketMessage,
  PlayerConnectedPayload,
  GameUpdatedPayload,
  FullStatePayload,
  ErrorPayload,
  LogUpdatePayload,
  PlayerConnectPayload,
  StateErrorDto,
  VPGranterDto,
  TriggeredEffectDto,
  MessageType,
  GamePhase,
  GameStatus,
  PlayerStatus,
  CardType,
  StandardProject,
} from "../../frontend/src/types/generated/api-types.js";

export {
  GamePhaseWaitingForGameStart,
  GamePhaseStartingSelection,
  GamePhaseStartGameSelection,
  GamePhaseAction,
  GamePhaseProductionAndCardDraw,
  GamePhaseComplete,
  GameStatusLobby,
  GameStatusActive,
  GameStatusCompleted,
  PlayerStatusSelectingStartingCards,
  PlayerStatusSelectingProductionCards,
  PlayerStatusWaiting,
  PlayerStatusActive,
} from "../../frontend/src/types/generated/api-types.js";
