uniform float uSphereRadius;
uniform float uZOffset;
uniform vec3 uSphereCenter;
varying vec4 vOceanWorldPosition;
varying vec3 vOceanNormal;
varying vec3 vWorldSphereNormal;
varying vec3 vOceanTangent;
varying vec3 vOceanBitangent;
varying vec2 vOceanUv;
varying vec3 vOceanViewNormal;
//#pragma body
vOceanUv = uv;
vec4 worldPos = modelMatrix * vec4(position, 1.0);
vec3 sphereDir = normalize(worldPos.xyz - uSphereCenter);
vec3 projectedPos = uSphereCenter + sphereDir * (uSphereRadius + uZOffset);
vOceanWorldPosition = vec4(projectedPos, 1.0);
vOceanNormal = normalize(mat3(modelMatrix) * normal);
vWorldSphereNormal = sphereDir;
vec3 upDir = abs(vOceanNormal.y) < 0.999 ? vec3(0.0, 1.0, 0.0) : vec3(1.0, 0.0, 0.0);
vOceanTangent = normalize(cross(upDir, vOceanNormal));
vOceanBitangent = cross(vOceanNormal, vOceanTangent);
vOceanViewNormal = normalize(normalMatrix * normal);
vec3 transformed = position;
